name       : deluge
version    : 2.0.3
release    : 16
source     :
    - https://ftp.osuosl.org/pub/deluge/source/2.0/deluge-2.0.3.tar.xz : 7e7ae8e6ca2a2bf0d487227cecf81e27332f0b92b567cc2bda38e47d859da891
license    : GPL-3.0-or-later
component  : network.download
summary    : A full-featured BitTorrent client
description: |
    Deluge is a full-featured BitTorrent client written in Python and GTK.
builddeps  :
    - python-wheel
    - intltool
rundeps    :
    - librsvg
    - libtorrent-rasterbar
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python-chardet
    - python-distro
    - python-geoip
    - python-openssl
    - python-rencode
    - python-pillow
    - python-setproctitle
    - python-six
    - python-twisted
    - python-zope.interface
    - pyxdg
    - xdg-utils
setup      : |
    # Mako is a dep of the Web UI. We don't need it
    sed "/'mako'/d" -i setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/{deluge-web,deluged}
    rm $installdir/usr/share/man/man1/{deluge-web,deluged}.1
    rm -rf $installdir/usr/lib/python*/site-packages/deluge/ui/web
