name       : deluge
version    : 2.0.5
release    : 22
source     :
    - https://ftp.osuosl.org/pub/deluge/source/2.0/deluge-2.0.5.tar.xz : c4bd04abfd211b65218be03f3c46d26f44024884de10e01859fb856fdd6f25d8
homepage   : https://deluge-torrent.org/
license    : GPL-3.0-or-later
component  : network.download
summary    : A full-featured BitTorrent client
description: |
    Deluge is a full-featured BitTorrent client written in Python and GTK.
builddeps  :
    - python-wheel
    - intltool
rundeps    :
    - librsvg
    - libtorrent-rasterbar
    - python-chardet
    - python-distro
    - python-geoip
    - python-gobject
    - python-openssl
    - python-rencode
    - python-pillow
    - python-setproctitle
    - python-six
    - python-twisted
    - python3-dbus
    - pyxdg
    - xdg-utils
setup      : |
    # Mako is a dep of the Web UI. We don't need it
    sed "/'mako'/d" -i setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/{deluge-web,deluged}
    rm $installdir/usr/share/man/man1/{deluge-web,deluged}.1
    rm -rf $installdir/usr/lib/python*/site-packages/deluge/ui/web
