name       : deluge
version    : 1.3.13
release    : 7
source     :
    - http://download.deluge-torrent.org/source/deluge-1.3.13.tar.bz2 : 37b3a22cea3ce8b87183f5d2d972d70db6e61825ea1c6bbc052e0120c49ee8c5
license    : GPL-3.0
component  : network.download
summary    : Deluge is a full-featured ​BitTorrent client for Linux, OS X, Unix and Windows.
description: |
    Deluge is a full-featured ​BitTorrent client for Linux, OS X, Unix and Windows.
builddeps  :
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtorrent-rasterbar)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(python-2.7)
    - intltool
    - python-chardet
    - python-openssl
    - python-setuptools
    - pyxdg
    - xdg-utils
rundeps    :
    - libtorrent-rasterbar
    - python-cryptography
    - python-chardet
    - python-openssl
    - python-service-identity
    - pyxdg
    - python-zope.interface
    - python-twisted
    - python-setuptools
    - python-gtk2
    - python-six
    - python-gobject2
    - python-cairo

build      : |
    %python_setup
install    : |
    %python_install
    # Remove the web cruft
    rm %installroot%/usr/bin/deluge-web
    rm %installroot%/usr/bin/deluged
    rm -rf %installroot%/usr/lib/python2.7/site-packages/deluge/ui/web
    rm -rf %installroot%/usr/share/man/man1/{deluge-web,deluged}.1
