name       : deluge
version    : 2.1.1
release    : 23
source     :
    - https://ftp.osuosl.org/pub/deluge/source/2.1/deluge-2.1.1.tar.xz : 768dd319802e42437ab3794ebe75b497142e08ed5b0fb2503bad62cef442dff7
homepage   : https://deluge-torrent.org/
license    : GPL-3.0-or-later
component  : network.download
summary    : A full-featured BitTorrent client
description: |
    Deluge is a full-featured BitTorrent client written in Python and GTK.
builddeps  :
    - python-wheel
    - intltool
rundeps    :
    - libayatana-appindicator
    - librsvg
    - libtorrent-rasterbar
    - python-chardet
    - python-distro
    - python-geoip
    - python-gobject
    - python-openssl
    - python-rencode
    - python-pillow
    - python-setproctitle
    - python-six
    - python-twisted
    - python3-dbus
    - pyxdg
    - xdg-utils
setup      : |
    # Mako is a dep of the Web UI. We don't need it
    sed "/'mako'/d" -i setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/{deluge-web,deluged}
    rm $installdir/usr/share/man/man1/{deluge-web,deluged}.1
    rm -rf $installdir/usr/lib/python*/site-packages/deluge/ui/web
